// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"definitelynotmusicbot/ent/guild"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	snowflake "github.com/disgoorg/snowflake/v2"
)

// GuildCreate is the builder for creating a Guild entity.
type GuildCreate struct {
	config
	mutation *GuildMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (gc *GuildCreate) SetName(s string) *GuildCreate {
	gc.mutation.SetName(s)
	return gc
}

// SetPlayerChannelID sets the "player_channel_id" field.
func (gc *GuildCreate) SetPlayerChannelID(s snowflake.ID) *GuildCreate {
	gc.mutation.SetPlayerChannelID(s)
	return gc
}

// SetNillablePlayerChannelID sets the "player_channel_id" field if the given value is not nil.
func (gc *GuildCreate) SetNillablePlayerChannelID(s *snowflake.ID) *GuildCreate {
	if s != nil {
		gc.SetPlayerChannelID(*s)
	}
	return gc
}

// SetPlayerMessageID sets the "player_message_id" field.
func (gc *GuildCreate) SetPlayerMessageID(s snowflake.ID) *GuildCreate {
	gc.mutation.SetPlayerMessageID(s)
	return gc
}

// SetNillablePlayerMessageID sets the "player_message_id" field if the given value is not nil.
func (gc *GuildCreate) SetNillablePlayerMessageID(s *snowflake.ID) *GuildCreate {
	if s != nil {
		gc.SetPlayerMessageID(*s)
	}
	return gc
}

// SetCreatedAt sets the "created_at" field.
func (gc *GuildCreate) SetCreatedAt(t time.Time) *GuildCreate {
	gc.mutation.SetCreatedAt(t)
	return gc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (gc *GuildCreate) SetNillableCreatedAt(t *time.Time) *GuildCreate {
	if t != nil {
		gc.SetCreatedAt(*t)
	}
	return gc
}

// SetUpdatedAt sets the "updated_at" field.
func (gc *GuildCreate) SetUpdatedAt(t time.Time) *GuildCreate {
	gc.mutation.SetUpdatedAt(t)
	return gc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (gc *GuildCreate) SetNillableUpdatedAt(t *time.Time) *GuildCreate {
	if t != nil {
		gc.SetUpdatedAt(*t)
	}
	return gc
}

// SetID sets the "id" field.
func (gc *GuildCreate) SetID(s snowflake.ID) *GuildCreate {
	gc.mutation.SetID(s)
	return gc
}

// Mutation returns the GuildMutation object of the builder.
func (gc *GuildCreate) Mutation() *GuildMutation {
	return gc.mutation
}

// Save creates the Guild in the database.
func (gc *GuildCreate) Save(ctx context.Context) (*Guild, error) {
	gc.defaults()
	return withHooks[*Guild, GuildMutation](ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GuildCreate) SaveX(ctx context.Context) *Guild {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GuildCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GuildCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GuildCreate) defaults() {
	if _, ok := gc.mutation.CreatedAt(); !ok {
		v := guild.DefaultCreatedAt()
		gc.mutation.SetCreatedAt(v)
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		v := guild.DefaultUpdatedAt()
		gc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GuildCreate) check() error {
	if _, ok := gc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Guild.name"`)}
	}
	if _, ok := gc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Guild.created_at"`)}
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Guild.updated_at"`)}
	}
	return nil
}

func (gc *GuildCreate) sqlSave(ctx context.Context) (*Guild, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = snowflake.ID(id)
	}
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GuildCreate) createSpec() (*Guild, *sqlgraph.CreateSpec) {
	var (
		_node = &Guild{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(guild.Table, sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = gc.conflict
	if id, ok := gc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := gc.mutation.Name(); ok {
		_spec.SetField(guild.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := gc.mutation.PlayerChannelID(); ok {
		_spec.SetField(guild.FieldPlayerChannelID, field.TypeUint64, value)
		_node.PlayerChannelID = &value
	}
	if value, ok := gc.mutation.PlayerMessageID(); ok {
		_spec.SetField(guild.FieldPlayerMessageID, field.TypeUint64, value)
		_node.PlayerMessageID = &value
	}
	if value, ok := gc.mutation.CreatedAt(); ok {
		_spec.SetField(guild.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := gc.mutation.UpdatedAt(); ok {
		_spec.SetField(guild.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Guild.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GuildUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (gc *GuildCreate) OnConflict(opts ...sql.ConflictOption) *GuildUpsertOne {
	gc.conflict = opts
	return &GuildUpsertOne{
		create: gc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Guild.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (gc *GuildCreate) OnConflictColumns(columns ...string) *GuildUpsertOne {
	gc.conflict = append(gc.conflict, sql.ConflictColumns(columns...))
	return &GuildUpsertOne{
		create: gc,
	}
}

type (
	// GuildUpsertOne is the builder for "upsert"-ing
	//  one Guild node.
	GuildUpsertOne struct {
		create *GuildCreate
	}

	// GuildUpsert is the "OnConflict" setter.
	GuildUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *GuildUpsert) SetName(v string) *GuildUpsert {
	u.Set(guild.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GuildUpsert) UpdateName() *GuildUpsert {
	u.SetExcluded(guild.FieldName)
	return u
}

// SetPlayerChannelID sets the "player_channel_id" field.
func (u *GuildUpsert) SetPlayerChannelID(v snowflake.ID) *GuildUpsert {
	u.Set(guild.FieldPlayerChannelID, v)
	return u
}

// UpdatePlayerChannelID sets the "player_channel_id" field to the value that was provided on create.
func (u *GuildUpsert) UpdatePlayerChannelID() *GuildUpsert {
	u.SetExcluded(guild.FieldPlayerChannelID)
	return u
}

// AddPlayerChannelID adds v to the "player_channel_id" field.
func (u *GuildUpsert) AddPlayerChannelID(v snowflake.ID) *GuildUpsert {
	u.Add(guild.FieldPlayerChannelID, v)
	return u
}

// ClearPlayerChannelID clears the value of the "player_channel_id" field.
func (u *GuildUpsert) ClearPlayerChannelID() *GuildUpsert {
	u.SetNull(guild.FieldPlayerChannelID)
	return u
}

// SetPlayerMessageID sets the "player_message_id" field.
func (u *GuildUpsert) SetPlayerMessageID(v snowflake.ID) *GuildUpsert {
	u.Set(guild.FieldPlayerMessageID, v)
	return u
}

// UpdatePlayerMessageID sets the "player_message_id" field to the value that was provided on create.
func (u *GuildUpsert) UpdatePlayerMessageID() *GuildUpsert {
	u.SetExcluded(guild.FieldPlayerMessageID)
	return u
}

// AddPlayerMessageID adds v to the "player_message_id" field.
func (u *GuildUpsert) AddPlayerMessageID(v snowflake.ID) *GuildUpsert {
	u.Add(guild.FieldPlayerMessageID, v)
	return u
}

// ClearPlayerMessageID clears the value of the "player_message_id" field.
func (u *GuildUpsert) ClearPlayerMessageID() *GuildUpsert {
	u.SetNull(guild.FieldPlayerMessageID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GuildUpsert) SetCreatedAt(v time.Time) *GuildUpsert {
	u.Set(guild.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GuildUpsert) UpdateCreatedAt() *GuildUpsert {
	u.SetExcluded(guild.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GuildUpsert) SetUpdatedAt(v time.Time) *GuildUpsert {
	u.Set(guild.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GuildUpsert) UpdateUpdatedAt() *GuildUpsert {
	u.SetExcluded(guild.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Guild.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(guild.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GuildUpsertOne) UpdateNewValues() *GuildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(guild.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Guild.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GuildUpsertOne) Ignore() *GuildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GuildUpsertOne) DoNothing() *GuildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GuildCreate.OnConflict
// documentation for more info.
func (u *GuildUpsertOne) Update(set func(*GuildUpsert)) *GuildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GuildUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *GuildUpsertOne) SetName(v string) *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GuildUpsertOne) UpdateName() *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.UpdateName()
	})
}

// SetPlayerChannelID sets the "player_channel_id" field.
func (u *GuildUpsertOne) SetPlayerChannelID(v snowflake.ID) *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.SetPlayerChannelID(v)
	})
}

// AddPlayerChannelID adds v to the "player_channel_id" field.
func (u *GuildUpsertOne) AddPlayerChannelID(v snowflake.ID) *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.AddPlayerChannelID(v)
	})
}

// UpdatePlayerChannelID sets the "player_channel_id" field to the value that was provided on create.
func (u *GuildUpsertOne) UpdatePlayerChannelID() *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.UpdatePlayerChannelID()
	})
}

// ClearPlayerChannelID clears the value of the "player_channel_id" field.
func (u *GuildUpsertOne) ClearPlayerChannelID() *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.ClearPlayerChannelID()
	})
}

// SetPlayerMessageID sets the "player_message_id" field.
func (u *GuildUpsertOne) SetPlayerMessageID(v snowflake.ID) *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.SetPlayerMessageID(v)
	})
}

// AddPlayerMessageID adds v to the "player_message_id" field.
func (u *GuildUpsertOne) AddPlayerMessageID(v snowflake.ID) *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.AddPlayerMessageID(v)
	})
}

// UpdatePlayerMessageID sets the "player_message_id" field to the value that was provided on create.
func (u *GuildUpsertOne) UpdatePlayerMessageID() *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.UpdatePlayerMessageID()
	})
}

// ClearPlayerMessageID clears the value of the "player_message_id" field.
func (u *GuildUpsertOne) ClearPlayerMessageID() *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.ClearPlayerMessageID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GuildUpsertOne) SetCreatedAt(v time.Time) *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GuildUpsertOne) UpdateCreatedAt() *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GuildUpsertOne) SetUpdatedAt(v time.Time) *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GuildUpsertOne) UpdateUpdatedAt() *GuildUpsertOne {
	return u.Update(func(s *GuildUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GuildUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GuildCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GuildUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GuildUpsertOne) ID(ctx context.Context) (id snowflake.ID, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GuildUpsertOne) IDX(ctx context.Context) snowflake.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GuildCreateBulk is the builder for creating many Guild entities in bulk.
type GuildCreateBulk struct {
	config
	builders []*GuildCreate
	conflict []sql.ConflictOption
}

// Save creates the Guild entities in the database.
func (gcb *GuildCreateBulk) Save(ctx context.Context) ([]*Guild, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Guild, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GuildMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = gcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = snowflake.ID(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GuildCreateBulk) SaveX(ctx context.Context) []*Guild {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GuildCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GuildCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Guild.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GuildUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (gcb *GuildCreateBulk) OnConflict(opts ...sql.ConflictOption) *GuildUpsertBulk {
	gcb.conflict = opts
	return &GuildUpsertBulk{
		create: gcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Guild.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (gcb *GuildCreateBulk) OnConflictColumns(columns ...string) *GuildUpsertBulk {
	gcb.conflict = append(gcb.conflict, sql.ConflictColumns(columns...))
	return &GuildUpsertBulk{
		create: gcb,
	}
}

// GuildUpsertBulk is the builder for "upsert"-ing
// a bulk of Guild nodes.
type GuildUpsertBulk struct {
	create *GuildCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Guild.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(guild.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GuildUpsertBulk) UpdateNewValues() *GuildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(guild.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Guild.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GuildUpsertBulk) Ignore() *GuildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GuildUpsertBulk) DoNothing() *GuildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GuildCreateBulk.OnConflict
// documentation for more info.
func (u *GuildUpsertBulk) Update(set func(*GuildUpsert)) *GuildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GuildUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *GuildUpsertBulk) SetName(v string) *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GuildUpsertBulk) UpdateName() *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.UpdateName()
	})
}

// SetPlayerChannelID sets the "player_channel_id" field.
func (u *GuildUpsertBulk) SetPlayerChannelID(v snowflake.ID) *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.SetPlayerChannelID(v)
	})
}

// AddPlayerChannelID adds v to the "player_channel_id" field.
func (u *GuildUpsertBulk) AddPlayerChannelID(v snowflake.ID) *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.AddPlayerChannelID(v)
	})
}

// UpdatePlayerChannelID sets the "player_channel_id" field to the value that was provided on create.
func (u *GuildUpsertBulk) UpdatePlayerChannelID() *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.UpdatePlayerChannelID()
	})
}

// ClearPlayerChannelID clears the value of the "player_channel_id" field.
func (u *GuildUpsertBulk) ClearPlayerChannelID() *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.ClearPlayerChannelID()
	})
}

// SetPlayerMessageID sets the "player_message_id" field.
func (u *GuildUpsertBulk) SetPlayerMessageID(v snowflake.ID) *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.SetPlayerMessageID(v)
	})
}

// AddPlayerMessageID adds v to the "player_message_id" field.
func (u *GuildUpsertBulk) AddPlayerMessageID(v snowflake.ID) *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.AddPlayerMessageID(v)
	})
}

// UpdatePlayerMessageID sets the "player_message_id" field to the value that was provided on create.
func (u *GuildUpsertBulk) UpdatePlayerMessageID() *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.UpdatePlayerMessageID()
	})
}

// ClearPlayerMessageID clears the value of the "player_message_id" field.
func (u *GuildUpsertBulk) ClearPlayerMessageID() *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.ClearPlayerMessageID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GuildUpsertBulk) SetCreatedAt(v time.Time) *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GuildUpsertBulk) UpdateCreatedAt() *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GuildUpsertBulk) SetUpdatedAt(v time.Time) *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GuildUpsertBulk) UpdateUpdatedAt() *GuildUpsertBulk {
	return u.Update(func(s *GuildUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GuildUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GuildCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GuildCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GuildUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
