// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	snowflake "github.com/disgoorg/snowflake/v2"
	"github.com/loukhin/probably-a-music-bot/ent/guild"
	"github.com/loukhin/probably-a-music-bot/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeGuild = "Guild"
)

// GuildMutation represents an operation that mutates the Guild nodes in the graph.
type GuildMutation struct {
	config
	op                   Op
	typ                  string
	id                   *snowflake.ID
	name                 *string
	player_channel_id    *snowflake.ID
	addplayer_channel_id *snowflake.ID
	player_message_id    *snowflake.ID
	addplayer_message_id *snowflake.ID
	created_at           *time.Time
	updated_at           *time.Time
	clearedFields        map[string]struct{}
	done                 bool
	oldValue             func(context.Context) (*Guild, error)
	predicates           []predicate.Guild
}

var _ ent.Mutation = (*GuildMutation)(nil)

// guildOption allows management of the mutation configuration using functional options.
type guildOption func(*GuildMutation)

// newGuildMutation creates new mutation for the Guild entity.
func newGuildMutation(c config, op Op, opts ...guildOption) *GuildMutation {
	m := &GuildMutation{
		config:        c,
		op:            op,
		typ:           TypeGuild,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withGuildID sets the ID field of the mutation.
func withGuildID(id snowflake.ID) guildOption {
	return func(m *GuildMutation) {
		var (
			err   error
			once  sync.Once
			value *Guild
		)
		m.oldValue = func(ctx context.Context) (*Guild, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Guild.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withGuild sets the old Guild of the mutation.
func withGuild(node *Guild) guildOption {
	return func(m *GuildMutation) {
		m.oldValue = func(context.Context) (*Guild, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m GuildMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m GuildMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Guild entities.
func (m *GuildMutation) SetID(id snowflake.ID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *GuildMutation) ID() (id snowflake.ID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *GuildMutation) IDs(ctx context.Context) ([]snowflake.ID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []snowflake.ID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Guild.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *GuildMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *GuildMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Guild entity.
// If the Guild object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GuildMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *GuildMutation) ResetName() {
	m.name = nil
}

// SetPlayerChannelID sets the "player_channel_id" field.
func (m *GuildMutation) SetPlayerChannelID(s snowflake.ID) {
	m.player_channel_id = &s
	m.addplayer_channel_id = nil
}

// PlayerChannelID returns the value of the "player_channel_id" field in the mutation.
func (m *GuildMutation) PlayerChannelID() (r snowflake.ID, exists bool) {
	v := m.player_channel_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPlayerChannelID returns the old "player_channel_id" field's value of the Guild entity.
// If the Guild object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GuildMutation) OldPlayerChannelID(ctx context.Context) (v *snowflake.ID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPlayerChannelID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPlayerChannelID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPlayerChannelID: %w", err)
	}
	return oldValue.PlayerChannelID, nil
}

// AddPlayerChannelID adds s to the "player_channel_id" field.
func (m *GuildMutation) AddPlayerChannelID(s snowflake.ID) {
	if m.addplayer_channel_id != nil {
		*m.addplayer_channel_id += s
	} else {
		m.addplayer_channel_id = &s
	}
}

// AddedPlayerChannelID returns the value that was added to the "player_channel_id" field in this mutation.
func (m *GuildMutation) AddedPlayerChannelID() (r snowflake.ID, exists bool) {
	v := m.addplayer_channel_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearPlayerChannelID clears the value of the "player_channel_id" field.
func (m *GuildMutation) ClearPlayerChannelID() {
	m.player_channel_id = nil
	m.addplayer_channel_id = nil
	m.clearedFields[guild.FieldPlayerChannelID] = struct{}{}
}

// PlayerChannelIDCleared returns if the "player_channel_id" field was cleared in this mutation.
func (m *GuildMutation) PlayerChannelIDCleared() bool {
	_, ok := m.clearedFields[guild.FieldPlayerChannelID]
	return ok
}

// ResetPlayerChannelID resets all changes to the "player_channel_id" field.
func (m *GuildMutation) ResetPlayerChannelID() {
	m.player_channel_id = nil
	m.addplayer_channel_id = nil
	delete(m.clearedFields, guild.FieldPlayerChannelID)
}

// SetPlayerMessageID sets the "player_message_id" field.
func (m *GuildMutation) SetPlayerMessageID(s snowflake.ID) {
	m.player_message_id = &s
	m.addplayer_message_id = nil
}

// PlayerMessageID returns the value of the "player_message_id" field in the mutation.
func (m *GuildMutation) PlayerMessageID() (r snowflake.ID, exists bool) {
	v := m.player_message_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPlayerMessageID returns the old "player_message_id" field's value of the Guild entity.
// If the Guild object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GuildMutation) OldPlayerMessageID(ctx context.Context) (v *snowflake.ID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPlayerMessageID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPlayerMessageID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPlayerMessageID: %w", err)
	}
	return oldValue.PlayerMessageID, nil
}

// AddPlayerMessageID adds s to the "player_message_id" field.
func (m *GuildMutation) AddPlayerMessageID(s snowflake.ID) {
	if m.addplayer_message_id != nil {
		*m.addplayer_message_id += s
	} else {
		m.addplayer_message_id = &s
	}
}

// AddedPlayerMessageID returns the value that was added to the "player_message_id" field in this mutation.
func (m *GuildMutation) AddedPlayerMessageID() (r snowflake.ID, exists bool) {
	v := m.addplayer_message_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearPlayerMessageID clears the value of the "player_message_id" field.
func (m *GuildMutation) ClearPlayerMessageID() {
	m.player_message_id = nil
	m.addplayer_message_id = nil
	m.clearedFields[guild.FieldPlayerMessageID] = struct{}{}
}

// PlayerMessageIDCleared returns if the "player_message_id" field was cleared in this mutation.
func (m *GuildMutation) PlayerMessageIDCleared() bool {
	_, ok := m.clearedFields[guild.FieldPlayerMessageID]
	return ok
}

// ResetPlayerMessageID resets all changes to the "player_message_id" field.
func (m *GuildMutation) ResetPlayerMessageID() {
	m.player_message_id = nil
	m.addplayer_message_id = nil
	delete(m.clearedFields, guild.FieldPlayerMessageID)
}

// SetCreatedAt sets the "created_at" field.
func (m *GuildMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *GuildMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Guild entity.
// If the Guild object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GuildMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *GuildMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *GuildMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *GuildMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Guild entity.
// If the Guild object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GuildMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *GuildMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the GuildMutation builder.
func (m *GuildMutation) Where(ps ...predicate.Guild) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the GuildMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *GuildMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Guild, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *GuildMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *GuildMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Guild).
func (m *GuildMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *GuildMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.name != nil {
		fields = append(fields, guild.FieldName)
	}
	if m.player_channel_id != nil {
		fields = append(fields, guild.FieldPlayerChannelID)
	}
	if m.player_message_id != nil {
		fields = append(fields, guild.FieldPlayerMessageID)
	}
	if m.created_at != nil {
		fields = append(fields, guild.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, guild.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *GuildMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case guild.FieldName:
		return m.Name()
	case guild.FieldPlayerChannelID:
		return m.PlayerChannelID()
	case guild.FieldPlayerMessageID:
		return m.PlayerMessageID()
	case guild.FieldCreatedAt:
		return m.CreatedAt()
	case guild.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *GuildMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case guild.FieldName:
		return m.OldName(ctx)
	case guild.FieldPlayerChannelID:
		return m.OldPlayerChannelID(ctx)
	case guild.FieldPlayerMessageID:
		return m.OldPlayerMessageID(ctx)
	case guild.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case guild.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Guild field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GuildMutation) SetField(name string, value ent.Value) error {
	switch name {
	case guild.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case guild.FieldPlayerChannelID:
		v, ok := value.(snowflake.ID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPlayerChannelID(v)
		return nil
	case guild.FieldPlayerMessageID:
		v, ok := value.(snowflake.ID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPlayerMessageID(v)
		return nil
	case guild.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case guild.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Guild field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *GuildMutation) AddedFields() []string {
	var fields []string
	if m.addplayer_channel_id != nil {
		fields = append(fields, guild.FieldPlayerChannelID)
	}
	if m.addplayer_message_id != nil {
		fields = append(fields, guild.FieldPlayerMessageID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *GuildMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case guild.FieldPlayerChannelID:
		return m.AddedPlayerChannelID()
	case guild.FieldPlayerMessageID:
		return m.AddedPlayerMessageID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GuildMutation) AddField(name string, value ent.Value) error {
	switch name {
	case guild.FieldPlayerChannelID:
		v, ok := value.(snowflake.ID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPlayerChannelID(v)
		return nil
	case guild.FieldPlayerMessageID:
		v, ok := value.(snowflake.ID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPlayerMessageID(v)
		return nil
	}
	return fmt.Errorf("unknown Guild numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *GuildMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(guild.FieldPlayerChannelID) {
		fields = append(fields, guild.FieldPlayerChannelID)
	}
	if m.FieldCleared(guild.FieldPlayerMessageID) {
		fields = append(fields, guild.FieldPlayerMessageID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *GuildMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *GuildMutation) ClearField(name string) error {
	switch name {
	case guild.FieldPlayerChannelID:
		m.ClearPlayerChannelID()
		return nil
	case guild.FieldPlayerMessageID:
		m.ClearPlayerMessageID()
		return nil
	}
	return fmt.Errorf("unknown Guild nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *GuildMutation) ResetField(name string) error {
	switch name {
	case guild.FieldName:
		m.ResetName()
		return nil
	case guild.FieldPlayerChannelID:
		m.ResetPlayerChannelID()
		return nil
	case guild.FieldPlayerMessageID:
		m.ResetPlayerMessageID()
		return nil
	case guild.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case guild.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Guild field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *GuildMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *GuildMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *GuildMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *GuildMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *GuildMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *GuildMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *GuildMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Guild unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *GuildMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Guild edge %s", name)
}
