// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/loukhin/probably-a-music-bot/ent/guild"
	"github.com/loukhin/probably-a-music-bot/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	guildFields := schema.Guild{}.Fields()
	_ = guildFields
	// guildDescCreatedAt is the schema descriptor for created_at field.
	guildDescCreatedAt := guildFields[4].Descriptor()
	// guild.DefaultCreatedAt holds the default value on creation for the created_at field.
	guild.DefaultCreatedAt = guildDescCreatedAt.Default.(func() time.Time)
	// guildDescUpdatedAt is the schema descriptor for updated_at field.
	guildDescUpdatedAt := guildFields[5].Descriptor()
	// guild.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guild.DefaultUpdatedAt = guildDescUpdatedAt.Default.(func() time.Time)
	// guild.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guild.UpdateDefaultUpdatedAt = guildDescUpdatedAt.UpdateDefault.(func() time.Time)
}
