-- Create "guilds" table
CREATE TABLE "guilds" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "player_channel_id" bigint NULL, "player_message_id" bigint NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "guilds_player_channel_id_key" to table: "guilds"
CREATE UNIQUE INDEX "guilds_player_channel_id_key" ON "guilds" ("player_channel_id");
-- Create index "guilds_player_message_id_key" to table: "guilds"
CREATE UNIQUE INDEX "guilds_player_message_id_key" ON "guilds" ("player_message_id");
